### ISSUE TITLE
Domain expired (infinite-labs.net), download binary?

### ISSUE THREAD

**Issue by luckyshot** [vjt/afloat#10]
Oops! When opening the website you get:

> This domain (infinite-labs.net) expired on 23/10/2018. You can retrieve your domain by clicking here.

Any other place from where to download the binaries?

**Comment by luckyshot** [comment]
Sorted!

Here's the releases page: https://github.com/vjt/afloat/releases/latest

**Comment by vjt** [comment]
:-) However I built that long ago and it may well need a rebuild for newer macOS versions... let me know how it goes.
